name: prodigy_ad_02
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # For IOS style icons
  cupertino_icons: ^1.0.8

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Generate RFC4122
  uuid: ^4.5.0

  # Provides internationalization and localization facilities
  intl: ^0.19.0

  # Animation
  animate_do: ^3.3.4

  # Dialogs
  panara_dialogs: ^0.1.5

  # Animations exported as json
  lottie: ^3.1.2

  # Toast
  ftoast: ^2.0.0

  # Slider
  flutter_slider_drawer: ^2.1.3

  # Date Picker
  flutter_cupertino_date_picker_fork: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_photo.jpg
